
name: Build Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build Go App
      run: |
        cd config/atlas_go
        go build -v ./...

  build-node:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Dependencies and Build Node App
      run: |
        cd data/react-ui
        npm install
        npm run build
